[project]
name = "biome-sync"
version = "0.1.0"
description = "A tool to synchronize Biome configurations across multiple projects."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
biomesync = "biome_sync.main:main"